name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner (similar to Slave01)

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Image
        run: |
          cd backend
          docker build -t mohamedessam1911/recipe-finder-backend:latest .

      - name: Build Frontend Image
        run: |
          cd frontend
          docker build -t mohamedessam1911/recipe-finder-frontend:latest .

      - name: Docker Login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker Images
        run: |
          docker push mohamedessam1911/recipe-finder-backend:latest
          docker push mohamedessam1911/recipe-finder-frontend:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

