name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t mohamedessam1911/recipe-finder-backend:latest ./backend
          docker push mohamedessam1911/recipe-finder-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t mohamedessam1911/recipe-finder-frontend:latest ./frontend
          docker push mohamedessam1911/recipe-finder-frontend:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Set up kubeconfig for Minikube
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          echo "${{ secrets.KUBE_CA_CERT }}" > ~/.kube/ca.crt
          echo "${{ secrets.KUBE_CLIENT_CERT }}" > ~/.kube/client.crt
          echo "${{ secrets.KUBE_CLIENT_KEY }}" > ~/.kube/client.key

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
        env:
          KUBECONFIG: ~/.kube/config

